### ISSUE TITLE
node-opus not working on Ubuntu

### ISSUE THREAD

**Issue by seneaLL** [Rantanen/node-opus#100]
* **Node Version**: node: v10.15.2 npm: 5.8.0
* **Platform**: Ubuntu 19.04
* **Compiler**: node.js
* **Module**: node-opus@0.3.3

During installation, node-opus sends many such warnings(photo), then say that the installation is complete, but it does not work during the test. Everything works well on windows. 

![Photos](https://user-images.githubusercontent.com/23480978/77909037-44e87500-7295-11ea-9bd0-e287d439f1b0.png)

**Comment by Rantanen** [comment]
I'm archiving the repository for lack of interest in maintaining it. Sorry I never got to deal with this issue. Please see [@discordjs/opus](https://github.com/discordjs/opus) for an alternative implementation that is based this project but uses more stable Node.js module technology that should break less between Node.js versions.
