### ISSUE TITLE
opus.Encoder._pushEncodedBuffer

### ISSUE THREAD

**Issue by vinnitu** [Rantanen/node-opus#101]
Hello!

I have stream of encoded opus packets.
I know rate, channels number and frameSize.
I need write ogg file.
I wrote something like this

```js
var opusEncoderStream = new opus.Encoder(rate, channels, frameSize);
var oggEncoder = new ogg.Encoder();
var fileStream = fs.createWriteStream('file.ogg');

opusEncoderStream.pipe(oggEncoder.stream()).pipe(fileStream);

while (encodedBuffer) { // read encoded opus data
   opusEncodeStream._pushEncodedBuffer(encodedBuffer);
}
```

But I get nothing in file.ogg
Tell me what else I need to do?

Thanks.

**Comment by vinnitu** [comment]
It works, but seems audio has not time stampes inside.
vlc player for example plays it wrong.
ffplay plays normal.
browser plays normal but doest show full time info.

```js
var fileStream = fs.createWriteStream('file.ogg');
var oggEncoder = new ogg.Encoder();
oggEncoder.pipe(fileStream);

var opusEncoderStream = new opus.Encoder(rate, channels, frameSize);
opusEncoderStream.pipe(oggEncoder.stream())

while (encodedBuffer) { // read encoded opus data
   opusEncodeStream._pushEncodedBuffer(encodedBuffer);
}
```

How to fix time problem?

Thanks.

**Comment by Rantanen** [comment]
I'm archiving the repository for lack of interest in maintaining it. Sorry I never got to deal with this issue. Please see [@discordjs/opus](https://github.com/discordjs/opus) for an alternative implementation that is based this project but uses more stable Node.js module technology that should break less between Node.js versions.
