### ISSUE TITLE
Config for win32 ia32

### ISSUE THREAD

**Issue by Cjen1** [Rantanen/node-opus#11]
I'm running this on a small bot with ia32 architecture, is there any way for you to add that as a supported architecture? I'm having issues creating a config file for it on a windows pc.

**Comment by Rantanen** [comment]
I'm archiving the repository for lack of interest in maintaining it. Sorry I never got to deal with this issue. Please see [@discordjs/opus](https://github.com/discordjs/opus) for an alternative implementation that is based this project but uses more stable Node.js module technology that should break less between Node.js versions.
