### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by MatusBoa** [Rantanen/node-opus#14]
Hello, when i try to install node-opus, im getting this error

[http://pastebin.com/d5fsySvG](http://pastebin.com/d5fsySvG)

**Comment by Rantanen** [comment]
Hey,

Which version of Visual Studio are you using? This seems to be an issue with node-gyp/VisualStudio setup. Are you able to install other packages that use native modules?

http://stackoverflow.com/questions/21069699/node-packages-not-building-on-windows-8-1-missing-microsoft-cpp-default-props

**Comment by MatusBoa** [comment]
Now im getting this error http://pastebin.com/XKirLtmC
In C:\Program Files (x86)\MSBuild\Micros oft.Cpp\v4.0\ i have only v140 not v120 and when i try to force to use v140 i get this error http://pastebin.com/GPEX5W3d

**Comment by Rantanen** [comment]
Needs more information on the environment.

I'm guessing you're running VS2015 based on having the v140 C++ targets for MSBuild?
Is that Windows 10?
And you're going for a 64-bit build?

Also can you run the install with `--verbose` option?

**Comment by MatusBoa** [comment]
Yes i have VS2015 with v140 c++ and windows 10.
I installed this https://www.microsoft.com/en-us/download/details.aspx?id=49983

There is output from console with `--verbose` http://pastebin.com/Ye9HqLHp

**EDIT:** npm-debug.log = http://pastebin.com/iTsGHVWQ

**Comment by Rantanen** [comment]
You are building the 32-bit configuration:

```
Project "D:\Laragon\www\node_modules\node-opus\build\binding.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Release|Win32".
```

Unfortunately we don't have 32-bit config in the repository: https://github.com/Rantanen/node-opus/tree/master/deps/config/opus/win

You could try making a `win32` directory there and copying the `x64/config.h` and `version.h` over. This should fix the `config.h` error - but I'm not sure if the x64 config.h works with the win32-build without changes.

**Comment by MatusBoa** [comment]
Can I change something so it will use 64 bit version ?
I dont understand this

**Comment by Rantanen** [comment]
No idea. Do you have 32-bit Node installed? You can use the following instructions to check that:

http://stackoverflow.com/questions/24956691/how-to-determine-whether-i-have-64bit-or-32-bit-node-executable-installed

**Comment by MatusBoa** [comment]
I installed x64 but it still says win32

**Comment by ChlckenWings** [comment]
Yeah I get config.h error. I hope you guys can make a 32 bit version

**Comment by Rantanen** [comment]
We can't - until _someone_ who has a 32-bit installation contributes a 32-bit config.h. :)
