### ISSUE TITLE
Critical Error

### ISSUE THREAD

**Issue by medallyon** [Rantanen/node-opus#15]
[Full Debug Log](http://pastebin.com/4rsrpX8N)

Loving the module, but can't get this installed on my 64-Bit Windows v8.1 with 64-Bit Node (v4.4.3). I keep getting the above error.

I've reinstalled VS 2015 multiple times (VS 2010 couldn't be found online). I've also installed multiple SDKs in hope that'd help, without avail. Re-installed Node too. Hell, I bet reinstalling my system wouldn't help.

Any help is greatly appreciated as I need this quite urgently :pensive:

**Comment by Rantanen** [comment]
That error message is absolutely useless. :(

I'm guessing it is the npm debug log? npm/npm#9347

Anyway... I have a feeling that is a Node compatibility issue. I don't think I've tried compiling it with Node 1.0.0 or greater and seems 4.0.0 broke the native API badly. The builds are failing bad on my system as well with newer Node.

I'll port this to new Nan and hopefully that fixes it. Should be ready in hour or three.

**Comment by Rantanen** [comment]
... now I feel extremely silly. This was already done for Node 4.0.0 but my local copy wasn't up to date. :)

**Comment by Rantanen** [comment]
\o/ But that doesn't make it Node 6.0.0 compatible still. (Feeling a bit less silly now)

**Comment by medallyon** [comment]
Soo.. What can I do to fix this error? btw the specific error would be:

``````
> ref@1.3.2 install C:\Users\Medallyon\node_modules\node-opus\node_modules\ogg-packet\node_modules\ref-struct\node_modules\ref
> node-gyp rebuild


C:\Users\Medallyon\node_modules\node-opus\node_modules\ogg-packet\node_modules\ref-struct\node_modules\ref>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild ) 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [C:\Users\Medallyon\node_modules\node-opus\node_modules\ogg-packet\node_modules\ref-struct\node_modules\ref\build\binding.vcxproj]```
``````

**Comment by Rantanen** [comment]
Just published Node-opus v0.1.13 to NPM. Can you try if you have any more luck with this?

If it still fails, can you copy the output of npm install from the command prompt here instead of the debug log?

**Comment by Rantanen** [comment]
Oh.. failed to locate CL. That looks like a system issue. :(

**Comment by Rantanen** [comment]
(Also that's ogg-packet, not node-opus itself that's failing to build)

**Comment by Rantanen** [comment]
If you open `Developer Command Prompt for VS2015` (should be available in the start menu somewhere under VS2015. Just search for it) and type `cl`, does it find the command?

**Comment by medallyon** [comment]
`'cl' is not recognised as an internal or external command, operable program or batch file.`

**Comment by Rantanen** [comment]
Looks like you're missing C++ compiler. Did you tick the C++ tools box when you were installing VS2015? It's not installed by default when you install Visual Studio.

**Comment by medallyon** [comment]
I've reinstalled some compilers when I installed some SDKs. I'll reinstall the C++ compiler and report back.

**Comment by Rantanen** [comment]
It should be part of the VS2015 installation package. You need to customize the installation when it asks whether to install with the normal components or with custom ones.

The C++ compiler is hidden somewhere in the checkbox tree it'll show.

**Comment by medallyon** [comment]
This might take some time. Thanks for taking the time to help me with this, although it's not even your module :+1:

**Comment by medallyon** [comment]
The reinstall was a total success!
The installation of node-opus came with no errors this time, although there were one or two warnings. W/E. Thanks.

**Comment by Rantanen** [comment]
Yeah, there's two or three warnings as far as I remember. I didn't remember off the top of my head the size_t vs int32 differences so I just left them in for now.

Good to hear you got it working! :)
