### ISSUE TITLE
input sample rate should not be used as the decoder rate

### ISSUE THREAD

**Issue by chris-rudmin** [Rantanen/node-opus#20]
https://github.com/Rantanen/node-opus/blob/master/lib/Decoder.js#L57
The sample rate defined in the header here is strictly informational and should not be used to determine the decoder sample rate (nor encoder).  See https://wiki.xiph.org/OggOpus#ID_Header

**Comment by chris-rudmin** [comment]
I'm not sure if in node there is a way to determine the device sample rate and implement the logic as specified in the xiph wiki: 

`An Ogg Opus player SHOULD select the playback sample rate according to the following procedure: 
If the hardware supports 48 kHz playback, decode at 48 kHz,
else if the hardware's highest available sample rate is a supported rate, decode at this sample rate,
else if the hardware's highest available sample rate is less than 48 kHz, decode at the next higher supported rate and resample,
else decode at 48 kHz and resample.`

**Comment by rotem925** [comment]
That's indeed an issue,
Also, when you emit the format event. You should not emit the original sample rate, but the encoded sample rate.

**Comment by Rantanen** [comment]
Pushed #21 to npm, so this should be fixed.

**Comment by Rantanen** [comment]
(Oh, and thanks for reporting it!)

**Comment by rotem925** [comment]
Hi,
The latest version in npm is still 0.2.2..

**Comment by Rantanen** [comment]
Oh dammit.

The publish hadn't gone through for some reason or another and I didn't actually confirm the message. Published now again - and this time I actually read what npm publish said in the end. :)

**Comment by rotem925** [comment]
Hehe,
Looks good now 😃 thanks!

**Comment by rotem925** [comment]
Hi,
version 0.2.3 still contains the previous version.
Can you please make sure you release the latest master branch?

Thanks,
Rotem

**Comment by Rantanen** [comment]
Oh crap. So sorry for that!

Doing a git rebase really shouldn't have been that hard. For some reason I completely forgot that, being all satisfied with just fetching the merge.

Okay it finally should be there. At least `npm install node-opus` gave me a version with the following changes in:

``` javascript
        this.emit( 'format', {
        channels: this.channels,
        sampleRate: this.rate,
...
        this.encoder = new OpusEncoder( this.rate, this.channels );
```

.. and it even seemed to pull that off npm instead of using some pre-existing `npm link` 😒

**Comment by rotem925** [comment]
And it works great now!!!

Thank you!

Rotem

**Comment by Rantanen** [comment]
Glad to hear. Sorry for the delays again!
