### ISSUE TITLE
Installiation failed

### ISSUE THREAD

**Issue by lordjbs** [Rantanen/node-opus#24]
Hey! My installation of node-opus failed! Here is the:
Log:
[Neues Textdokument.txt](https://github.com/Rantanen/node-opus/files/748165/Neues.Textdokument.txt)

**Comment by Rantanen** [comment]
Quickly going through the log, it seems like you're trying to install under the system32 directory in Windows. I'm not all that familiar with Node.js in Windows but that doesn't seem right. You sure this is what you want?

**Comment by lordjbs** [comment]
Oh, it installed to Win?! ima change the directory xD

**Comment by Rantanen** [comment]
You should either install it in the project directory using `npm install node-opus` in the project directory or globally using `npm install -g node-opus`.

**Comment by lordjbs** [comment]
Now its saying:
http://prntscr.com/e3md6r

**Comment by lordjbs** [comment]
K, i really dont know why its dont work

**Comment by hydrabolt** [comment]
Run `npm install --global windows-build-tools`

**Comment by amishshah** [comment]
Try installing the [Windows 8.1 SDK](https://developer.microsoft.com/en-us/windows/downloads/windows-8-1-sdk)
