### ISSUE TITLE
Decoding packet by packet from udp broadcast

### ISSUE THREAD

**Issue by Madshyson** [Rantanen/node-opus#34]
Hello !,
I'm currently developping a web application in node js, 
I'm trying to use this module to decode encoded Opus packet diffused by a wifi broadcast, and read the result through the speakers.

I'm having trouble using the first method displayed on the readme : "var decoded = encoder.decode( encoded, frame_size );". 

Received packets can have different size and some of them are crashing the decoder : "OPUS_INVALID_PACKET" .
the few decoded packets when writed in the speaker are messy.

I have no trouble decoding the incoming packets using the Opus librairy on an android app.

Any insight whould be appreciated !
Have a great day!

**Comment by Rantanen** [comment]
Sorry, I've been unable to come up with any response to this one without knowing more about the setup.

Are you certain the packets in the broadcast are raw Opus frames and not something like Ogg packets?

In my experience raw Opus frames are very rare in the wild. I'm assuming you don't mean [the Opus library](http://opus-codec.org/release/stable/2017/06/26/libopus-1_2_1.html) when you mention "the Opus library" on Android?

**Comment by Rantanen** [comment]
I'm archiving the repository for lack of interest in maintaining it. Sorry I never got to deal with this issue. Please see [@discordjs/opus](https://github.com/discordjs/opus) for an alternative implementation that is based this project but uses more stable Node.js module technology that should break less between Node.js versions.
