### ISSUE TITLE
Installation Failed.

### ISSUE THREAD

**Issue by DomTrues** [Rantanen/node-opus#36]
The installation of this module failed, I have already installed the module 'windows-build-tools' successfully, but for some reason, it still won't work:

The error:
https://hastebin.com/exuwayapun.tex

**Comment by Rantanen** [comment]
`(current: {"os":"win32","arch":"ia32"})`

This seems like you're running 32-bit Windows? This isn't currently supported as I haven't been able to source 32-bit Windows config.h from anywhere.

You can try installing this by copying the `deps/config/opus/win/x64/config.h` and `version.h` into `deps/config/opus/win/ia32/` and it might just work. The config file didn't seem all that complicated.

Unfortunately I don't have a 32-bit Windows development machine to test this with so I'm wary of making the change myself and claiming 32-bit support.
