### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by vothvovo** [Rantanen/node-opus#37]
### I'm getting this error when i try to install node-opus:

`E:\Discord Bot>npm install node-opus

> ref@1.3.4 install E:\Discord Bot\node_modules\ref
> node-gyp rebuild

E:\Discord Bot\node_modules\ref>if not defined npm_config_node_gyp (node "E:\Node.js\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (E:\Node.js\node_modules\npm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at E:\Node.js\node_modules\npm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at E:\Node.js\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "E:\\Node.js\\node.exe" "E:\\Node.js\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\Discord Bot\node_modules\ref
gyp ERR! node -v v6.11.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

> node-opus@0.2.6 install E:\Discord Bot\node_modules\node-opus
> node-gyp rebuild

E:\Discord Bot\node_modules\node-opus>if not defined npm_config_node_gyp (node "E:\Node.js\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (E:\Node.js\node_modules\npm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at E:\Node.js\node_modules\npm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at E:\Node.js\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "E:\\Node.js\\node.exe" "E:\\Node.js\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\Discord Bot\node_modules\node-opus
gyp ERR! node -v v6.11.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN discord.js@11.1.0 requires a peer of bufferutil@^3.0.0 but none was installed.
npm WARN discord.js@11.1.0 requires a peer of erlpack@hammerandchisel/erlpack but none was installed.
npm WARN discord.js@11.1.0 requires a peer of opusscript@^0.0.3 but none was installed.
npm WARN discord.js@11.1.0 requires a peer of sodium@^2.0.1 but none was installed.
npm WARN discord.js@11.1.0 requires a peer of libsodium-wrappers@^0.5.1 but none was installed.
npm WARN discord.js@11.1.0 requires a peer of uws@^0.14.1 but none was installed.
npm WARN discord_bot@0.0.1 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ref@1.3.4 (node_modules\ref):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ref@1.3.4 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "E:\\Node.js\\node.exe" "E:\\Node.js\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-opus"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-opus@0.2.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-opus@0.2.6 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-opus package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-opus
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-opus
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Discord Bot\npm-debug.log`

I already tried so much things but it just wont work, so thats why im posting here. Thanks for any help.

**Comment by Rantanen** [comment]
The first error message in the output is:

```
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack at failNoPython (E:\Node.js\node_modules\npm\node_modules\node-gyp\lib\configure.js:449:14)
```

So my guess is that your build environment isn't set up. Try installing https://www.npmjs.com/package/windows-build-tools
