### ISSUE TITLE
Support ogg-containers with node-ogg

### ISSUE THREAD

**Issue by Rantanen** [Rantanen/node-opus#4]
Support the stream interface required by node `ogg`.

Initial work started by @nfriedly: https://gist.github.com/nfriedly/c4549e76440d7e703d43

Will try to take a look at this in the evening today.

**Comment by Rantanen** [comment]
Initial version is done in 0ca50df727a79b6fd94377c6e1a. There's still some problems with multi-channel streams I believe, but in general it should work.

Examples in `test/decode-file.js` and `test/encode-file.js`.

(Oh and `node-ogg` should now be v0.12 compatible! \o/)

**Comment by nfriedly** [comment]
Awesome! :+1: :+1:

**Comment by nfriedly** [comment]
Sorry to be an Instant PITA, but I'm getting the following error now:

```
/Users/nfriedly/player/node_modules/speaker/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/Users/nfriedly/player/node_modules/speaker/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/nfriedly/player/node_modules/speaker/index.js:8:34)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

**Comment by nfriedly** [comment]
Oh, wait, that isn't even yours.

**Comment by Rantanen** [comment]
Was about to say. :D

(Although I wouldn't be surprised if it was caused by mine!)

**Comment by nfriedly** [comment]
No, it's because I'm an idiot and switched back to node 0.12 but didn't rebuild the dependencies :P

**Comment by nfriedly** [comment]
Ok, so now that I have things set up properly, it looks like speaker is choking because it expects an object to go along with `format` events, (and then it adjusts itself to match the object). It tries to call `Object.keys()` on the nothing that you pass along with your `format` event which doesn't work out so well...

Do you think you can pass an object along with the channels and frequency and such? (or, alternatively, not fire a `format` event)

**Comment by Rantanen** [comment]
In any case the "some problems with multi-channel streams" might have been an understatement: I've tested it with one stereo file and it segfaulted. I did get it working with a third party mono Opus file though (http://xiph.org/~giles/2012/opus/detodos.opus) so I'm confident I did get some parts of it right.

Didn't give it really extensive testing though.

Also there's something weird with the output as there seems to be 1 frame worth of silent audio at the start. No idea what causes that, didn't poke my head too far in the Opus standard.

So it's not ideal and it will most likely break on random files (Files with Opus tags spanning multiple Ogg pages, etc.), but it's a start.

The rest should follow later, but not tonight.

**Comment by Rantanen** [comment]
Oh that I can do. Any idea where the 'format' event is documented?

**Comment by nfriedly** [comment]
https://github.com/TooTallNate/node-speaker#new-speaker-format----speaker-instance

**Comment by nfriedly** [comment]
And, BTW, I definitely owe you a beer ;)

**Comment by Rantanen** [comment]
The format parameters should be there. It's missing the samplesPerFrame, but that's up to the client anyway and not dependent on the Opus stream.

**Comment by nfriedly** [comment]
IT WORKS!!!! Testing on the Pi in a moment....

**Comment by Rantanen** [comment]
Woo! I should catch some rest tonight, but now I'm too curious to leave. :)

**Comment by nfriedly** [comment]
(sorry, stopped for dinner while it was compiling.) I'm having touble with getting `ogg` to install. I think I'm going to send nate a bug report and then I need to call it a night as well though.
