### ISSUE TITLE
Encoding raw PCM stream fails with "TypeError: Invalid non-string/buffer chunk"

### ISSUE THREAD

**Issue by autonome** [Rantanen/node-opus#40]
On Mac OS X, and recording with the "mic" package from NPM, which uses SOX to access built-in mic.

Example code:

var rate = 16000;
var frame_size = rate/100;
var channels = 1;
var opus = require('node-opus');
var opusEncodeStream = new opus.Encoder(rate, channels, frame_size);
var outputFileStream = fs.WriteStream('stream.opus');
micInputStream.pipe(opusEncodeStream).pipe(outputFileStream);

It fails as soon as the stream starts with error: "TypeError: Invalid non-string/buffer chunk"

I can record the same way with the "mic" package, write the raw stream to file, and encoding works fine here:

opusenc --raw --raw-rate 16000 --raw-chan 1 stream.raw stream.opus

**Comment by autonome** [comment]
I tried encoding the buffer but that makes the script die instantly, no errors or anything:

var opus = require('node-opus');
var rate = 16000;
var encoder = new opus.OpusEncoder(rate);
var frame_size = rate / 100;
var encoded = encoder.encode(buffer, frame_size);

**Comment by Rantanen** [comment]
What's the `buffer.length` in the latter one? `encoder.encode` calls more or less directly [`opus_encode`](https://mf4.xiph.org/jenkins/view/opus/job/opus/ws/doc/html/group__opus__encoder.html) of the underlying opus native library.

Essentially it needs to be 2.5, 5, 10, 20, 40 or 60 ms of audio. (40, 80, 160, 320, 640 or 960 samples with 16000 Hz sample rate.)

The `frame_size` parameter you are giving isn't a frame size but `OPT_INT_ARG( 1, maxPacketSize, MAX_PACKET_SIZE );` which limits the encoded packet size.

_(Edit: The underlying opus library is notoriously bad for burning down with invalid parameters. Our `Encoder` and `Decoder` types attempt to do some parameter checking but the low level `OpusEncoder` really doesn't do any.)_

The issue with your initial attempt to use `Encoder` is that `Encoder` isn't a file stream. It emits individual Opus frames, which is most certainly not what you want in your file. You'll need a container, such as _ogg_ (which is what `opusenc` uses) to store these packets in an audio file.

The good news is that the `Encoder` should be compatible with TooTallNate's [ogg](https://www.npmjs.com/package/ogg) package. See the [mp3-to-ogg](https://github.com/Rantanen/node-opus/blob/master/examples/mp3-to-ogg.js) for an example of piping the opus frames into the ogg container.

**Comment by autonome** [comment]
Thanks very much for explaining!

Using the ogg module results in a file that:

* plays back just fine in Firefox and Vox, but the leading and following
silence have disappeared...

* crashes VLC - wait... I updated to latest VLC, and doesn't crash, but
says audio duration is 0:00, so plays back nothing

* gets "cannot open file" error in Quicktime

If I do `opusinfo` on the resulting file, I see some errors:

WARNING: Samples with negative granpos in stream 1
WARNING: Sample count ahead of granule (960>640) in stream 1
... many more of these

and at the end I get:

ERROR: stream 1 has interior holes or more than one page of end trimming

Do you know if these are significant?

**Comment by autonome** [comment]
Current code looks like:

```
var rate = 16000;
var max_packet_size = rate / 100;
var channels = 1;
var opus = require('node-opus');
var opusEncodeStream = new opus.Encoder(rate, channels, max_packet_size);
var ogg = require('ogg');
var oggEncoder = new ogg.Encoder();
var outputFileStream = fs.WriteStream('stream.opus');
micInputStream.pipe(opusEncodeStream).pipe(oggEncoder.stream());
oggEncoder.pipe(outputFileStream);
```

**Comment by autonome** [comment]
@Rantanen any ideas?

I'm most concerned by the opusinfo error.

"ERROR: stream 1 has interior holes or more than one page of end trimming"

**Comment by Rantanen** [comment]
I don't really.. Unfortunately I'm suspecting there's an issue with `ogg`...

I don't think node-opus deals with the granules at all.

**Comment by Rantanen** [comment]
I'll take that back! We do set the granulepos in `Encoder.js`.

I'll try to find a time to run the sample code later today or tomorrow and see if there's something weird going on with the `granulepos` calculations in `Encoder.js`..

**Comment by autonome** [comment]
Hm, another interesting test: Decode the resulting file from the code above, and play it back. The audio is sped up in the resulting wav file. The same file plays back fine in Firefox though.

```
opusdec --rate 16000 stream.opus stream.wav && play stream.wav
```

**Comment by Rantanen** [comment]
Completely my fault for not reading the specification. The granule position is not the total number of PCM samples with the given rate but the total number of PCM samples with rate of 48 kHz.

This meant anything but the 48 kHz sampling rate when encoding was off.

**Comment by Rantanen** [comment]
This should be part of the new 0.2.7 release in NPM. Just pushed that one.

Please reopen this issue if you still encounter problems with it.

**Comment by autonome** [comment]
FIXED!!! The opus file generated by the code above now works fine, can be
decoded normally with opusdec. Thank you so much for looking into this
@Rantanen!

**Comment by Rantanen** [comment]
Great! Thanks for sticking by - and sorry for the issues.

I should have probably written the code right in the first place. Would have saved us both some time. :)
