### ISSUE TITLE
Appreciable delays when immediately decoding from encoding.

### ISSUE THREAD

**Issue by JDvorak** [Rantanen/node-opus#41]
**[Read newest for current question concerning this toy case]**

I was writing a little sanity check test and discovered I cannot immediately encode and decode. Is there something I am missing in the code below? I am getting a bad headers error on the decoder. The sound coming through from generate is good, if I pull both encoder and decoder out I can hear it. Similarly, I can swap this out for `TooTallNate/node-lame` and with the same pattern encode-decode to the speaker just fine.

````js
var rate = 48000;
var frame_size = rate/100;
var opusEncodeStream = new opus.Encoder(rate, 2, frame_size);
var opusDecodeStream = new opus.Decoder(rate, 2, frame_size);
generate.pipe(opusEncodeStream).pipe(opusDecodeStream).pipe(speaker)
````

````bash
Error: Unhandled "error" event. (Bad header)
    at Decoder.emit (events.js:185:19)
    at Decoder.onerror (_stream_readable.js:664:12)
````

**Comment by JDvorak** [comment]
Ok, this works, for some reason because I saw ogg-packet being used, I figured the encoder was also wrapping things nicely in a bow. 

Thanks for the library!

````js
generate
.pipe(opusEncodeStream)
.pipe(oggEncoder.stream(num))
oggEncoder.pipe(oggDecoder)
oggDecoder.on( 'stream', function( stream ) {
    stream.pipe(opusDecodeStream).pipe(speaker)
});
````

**Comment by JDvorak** [comment]
I'm getting >100ms delays on playback from the microphone, using the code above.  I have been messing with the parameters: complexity, application mode, bandwidth, frame size, max frame size-- and in all cases, the delay largely remains! However, when I perform this same test on `abalabahaha/opusscript,` there is no delay (there is, however, a great deal of stuttering.)

Does anyone have any insight here into where the delay is coming from? I already tried swapping all the pipes with empty throughs and just running from mic to speaker, and the delay vanishes. I have the suspicion it is the oggDecoder, but I don't see a way to isolate it. Any suggestions?

**Comment by Rantanen** [comment]
I did some testing yesterday.

https://travis-ci.org/Rantanen/node-opus

> should decode 8000:1 random audio in 48000:2 Hz (75ms)

If I remember right, that 8000 sampling frequency test matches 2 seconds of audio - and the decode for the full 2+ seconds at 48 kHz stereo takes 75 ms on Travis. So there shouldn't be 100 ms delay on the decoding here.

On the other hand, there is some initialization delay involved. If you are streaming the audio from microphone to speakers with no buffering, you are limiting yourself to the maximum delay for the whole pipeline. If it takes libopus 100 ms to "warm up", then you will be 100 ms behind and you won't be catching up as there's no frame skipping in your pipeline.

If this was a real world application, you'd most certainly have a jitter buffer of some kind between the microphone and speakers. This would allow the buffer to duplicate audio frames in case the source is not providing them fast enough and also to skip audio frames in case the source is providing them faster than the sink is consuming them.

**Comment by Rantanen** [comment]
I'm archiving the repository for lack of interest in maintaining it. Sorry I never got to deal with this issue. Please see [@discordjs/opus](https://github.com/discordjs/opus) for an alternative implementation that is based this project but uses more stable Node.js module technology that should break less between Node.js versions.
