### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string/buffer

### ISSUE THREAD

**Issue by lostcodder** [Rantanen/node-opus#44]
events.js:193
      throw er; // Unhandled 'error' event
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string/buffer
    at validChunk (_stream_writable.js:255:10)
    at WriteStream.Writable.write (_stream_writable.js:289:21)
    at Encoder.ondata (_stream_readable.js:642:20)
    at emitOne (events.js:125:13)
    at Encoder.emit (events.js:221:7)
    at addChunk (_stream_readable.js:265:12)
    at readableAddChunk (_stream_readable.js:252:11)
    at Encoder.Readable.push (_stream_readable.js:209:10)
    at Encoder.Transform.push (_stream_transform.js:146:32)
    at Encoder._writeHeader (C:\Users\lostc\Back\projects\mic\node_modules\node-opus\lib\Encoder.js:74:10)

**Comment by Rantanen** [comment]
You need to elaborate the issue.

**Comment by Rantanen** [comment]
If this is still a problem, please re-open the issue with better description of the problem. The error message alone isn't sufficient.

**Comment by ekifox** [comment]
@Rantanen I'm reopening this.

(node:12552) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be one of type string or Buffer. Received type object
    at validChunk (_stream_writable.js:263:10)
    at WriteStream.Writable.write (_stream_writable.js:297:21)
    at Encoder.ondata (_stream_readable.js:706:20)
    at Encoder.emit (events.js:193:13)
    at Encoder.EventEmitter.emit (domain.js:481:20)
    at addChunk (_stream_readable.js:296:12)
    at readableAddChunk (_stream_readable.js:277:11)
    at Encoder.Readable.push (_stream_readable.js:232:10)
    at Encoder.Transform.push (_stream_transform.js:148:32)
    at Encoder._writeHeader (node_modules/node-opus/lib/Encoder.js:74:10)

**Comment by herenickname** [comment]
@Rantanen How to right write to file from opus.Encoder?

**Comment by Rantanen** [comment]
If you need raw opus frames, see: https://github.com/Rantanen/node-opus/blob/master/test/old/app.js

**Comment by herenickname** [comment]
@Rantanen I'm sorry, I will bring in a bit of offtopic, but I have a strange problem that I get at the time of preparing the buffer for your module.
My application begins to show signs of a Schrödinger cat when working with buffers :)

```js
const streams = {}
const encoder = new Opus(48000)

export function appendClientVoiceData(clientId: number, buffer: Buffer) {
	if (!streams[clientId]) {
		streams[clientId] = {
			createdAt: Date.now(),
			data: []
		}
	}

	console.log(buffer)

	streams[clientId].data.push(buffer)
}

export function endClientVoiceData(clientId: number) {
	if (!streams[clientId]) {
		return false
	}

	console.log(streams[clientId].data)

	for (const part of streams[clientId].data) {
		const rawAudio = encoder.decode(part)
		// ...
	}
}
```
My application calls the `appendClientVoiceData` function about 500 times per second with different clientId and buffer data.

When I need to start processing the received data, I call `endClientVoiceData` for the clientId I need and get that all the data in the `streams[clientId].data` become the same.

![image](https://user-images.githubusercontent.com/1989823/61535864-f8794400-aa3b-11e9-85ee-a0ce9f155be2.png)

A good illustration of what is happening.
First I call `appendClientVoiceData(100, recBuf)`
Then I write `console.log ('saaaave')`
and call `endClientVoiceData(100)`

Have you ever faced a similar?

I tried to clone the buffer before putting it in `streams[clientId].data`:
```js
const clone = Buffer.from(buffer)
streams[clientId].data.push(clone)
```
But it does not help. Just now there will be identical data with different addresses in memory :)

Tried on different latest versions of the node: 10, 11, 12

**Comment by Rantanen** [comment]
The current issue definitely seems like wherever you're receiving the data from is re-using the buffer. The `data.push` is just storing a reference to the buffer so anything that overwrites the buffer will alter the stored "data" as well.

`Buffer.from(...)` does _not_ clone the data [the documentation](https://nodejs.org/api/buffer.html#buffer_class_method_buffer_from_array) states "This creates a view of the ArrayBuffer without copying the underlying memory" (note that you'll need to check which version of `from` you are calling as the one using array-parameters _does_ clone the data).

You might need to use the `Buffer.copy` method instead.

**Comment by herenickname** [comment]
@Rantanen you are better than god
