### ISSUE TITLE
Installation Failed(Another One, I Know)

### ISSUE THREAD

**Issue by stevenvr-0548** [Rantanen/node-opus#45]
Hello,

Once installing, configuring and building the node-gyp successfully, and having the windows-build-tools installed and added to `PATH`, I still get an error when trying to install node-opus.

Error:

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\gebruiker\Documents\Discord Bots\CMFM!\node_modules\node-opus
gyp ERR! node -v v6.11.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\gebruiker\Documents\Discord Bots\CMFM!\node_modules\ref\package.json'
npm WARN discord.js@11.2.1 requires a peer of bufferutil@^3.0.2 but none was installed.
npm WARN discord.js@11.2.1 requires a peer of erlpack@hammerandchisel/erlpack but none was installed.
npm WARN discord.js@11.2.1 requires a peer of opusscript@^0.0.3 but none was installed.
npm WARN discord.js@11.2.1 requires a peer of sodium@^2.0.1 but none was installed.
npm WARN discord.js@11.2.1 requires a peer of libsodium-wrappers@^0.5.4 but none was installed.
npm WARN discord.js@11.2.1 requires a peer of uws@^0.14.5 but none was installed.
npm WARN CMFM!@1.0.0 No repository field.
npm WARN CMFM!@1.0.0 No license field.
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-opus"
npm ERR! node v6.11.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-opus@0.2.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-opus@0.2.7 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-opus package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-opus
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-opus
npm ERR! There is likely additional logging output above.

I tried almost everything now, fixed many errors on my own, and now I get this, which I can't fix for some reason. Been doing this for nearly 5 hours straight.

**Comment by Rantanen** [comment]
> npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\gebruiker\Documents\Discord Bots\CMFM!\node_modules\ref\package.json'

This seems like a problem with the ref package.

On the other hand that error message seems weird.

What have you done by now? Could you try making a new empty "CMFM!2" directory, navigating there and running the following commands:

```
npm init
npm install node-opus
```

**Comment by stevenvr-0548** [comment]
I have installed `windows-build-tools`, added the Python to my PATH variable, and did everything else I needed to do. I did not try to make an empty CMFM!2 directory, I will try it now.

**Comment by stevenvr-0548** [comment]
Unfortunately, this gives me the same error, I don't know what to do now.

**Comment by Rantanen** [comment]
what does `npm install ref` say?

**Comment by stevenvr-0548** [comment]
It installed successfully, should I try to install node-opus now?

**Comment by Rantanen** [comment]
That probably won't work.

When you executed `npm install node-opus`, there are no messages between `npm install node-opus` and the ERR! messages?

```
gyp ERR! build error
gyp ERR! stack Error: C:\Program Files\MSBuild\14.0\bin\msbuild.exe failed with exit code: 1
gyp ERR! stack at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
...
```

**Comment by stevenvr-0548** [comment]
Yes, there were. There are a lot of fatal errors which had to do with node-opus not being able to find a certain file for some reason.

Full load of messages can be found here(to avoid extreme messages):
https://hastebin.com/kawasexome.tex

**Comment by Rantanen** [comment]
Now that would have been helpful to begin with... :)

My guess is that you're running 32-bit Windows. As the [README.md](https://github.com/Rantanen/node-opus/blob/master/README.md) puts it:

> Supported platforms:
> - ...
> - Windows x64

You could try adding Win32 support by copying the 64-bit config.h and ensuring it builds properly. Unfortunately I don't have a 32-bit machine to test this with so I haven't done it.

**Comment by stevenvr-0548** [comment]
Yes, I am running 32-bit Windows, since my processor can't handle 64-bit. Could you explain to me how I can add Win32 support in detail?

**Comment by Rantanen** [comment]
1. Clone the node-opus repository.
2. Set up the 32-bit `config.h` and `version.h` files. These should probably go to: "deps/config/opus/win/ia32". Not sure about the last directory name.
3. Ensure 'npm test' executes successfully.

You can then then run `npm link` in the repository clone and `npm link node-opus` in your CMFM project folder to use the local version of `node-opus`. If you get it working on the 32-bit system, I'd be glad to take a PR on the config.h/version.h additions.

**Comment by stevenvr-0548** [comment]
I have one question left. The 32-bit `config.h` and `version.h` are set up by simply copying the 64-bit files into the ia32 directory?

Or do I need to follow the steps specified in the [README.md](https://github.com/Rantanen/node-opus/blob/master/README.md)?

**Comment by Rantanen** [comment]
If you got the Linux subsystem for Windows, you might be able to follow the autogen and configure steps listed in README.md.

However normally you can't so you need to come up with those files on your own.

Copying them from the 64-bit files is probably a start, but not guaranteed to work. You might start with that and see if that does the trick - but if there are any compilation issues, you'll need to edit the files by hand.

Oh, also there probably should be `npm install` command between the 2nd and 3rd step in the list above; before the `npm test`.

**Comment by Multiconcepted** [comment]
I tried copying `config.h` and `version.h` from `deps/config/opus/win/x64` to `deps/config/opus/win/ia32`, then ran:
- `npm link` in the `node-opus` repo
- `npm link node-opus` in a separate project repo
- `npm install <path to node-opus repo>`

It installed without the C1083 errors that I keep getting when trying to install node-opus and I am on 32-bit Windows 10.

**Comment by Rantanen** [comment]
I'm archiving the repository for lack of interest in maintaining it. Sorry I never got to deal with this issue. Please see [@discordjs/opus](https://github.com/discordjs/opus) for an alternative implementation that is based this project but uses more stable Node.js module technology that should break less between Node.js versions.
