### ISSUE TITLE
ImportError: No module named compiler.ast

### ISSUE THREAD

**Issue by mikuhl-dev** [Rantanen/node-opus#46]
I'm getting this error trying to `npm install node-opus`

I have already done `apt-get install build-essential`

What gives?

**Comment by Rantanen** [comment]
Build essential includes the system headers and C/C++ compilers (plus stuff).

The `ImportError: No module named compiler.ast` is a Python error message. Ensure you've got Python installed. Try doing `python --version` - the installed version should be 2.x (probably 2.7).

I believe you can install it with `apt-get install python2.7`, if it isn't installed already.

**Comment by mikuhl-dev** [comment]
`python --version` returns `Python 2.7.14` But using `apt-get install python2.7` made it work. Very strange that build-essential did not install the part of python that lets you build.

**Comment by Rantanen** [comment]
https://packages.ubuntu.com/xenial/build-essential

Build essential only includes the native development tools. It skips things like python, perl, etc. which are stilll required for various builds, such as node-gyp. Not sure how you ended up with python without python2.7 though.
