### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by samishii23** [Rantanen/node-opus#48]
https://pastebin.com/tQDVCisp
Note too sure whats going on with this. Any help would be appreciated. Thanks.

**Comment by ghost** [comment]
Just wondering, have you run `npm init`?

**Comment by ghost** [comment]
However I can't see any errors, it looks like it had installed fine. What is the problem that you are having? @samishii23

**Comment by Rantanen** [comment]
Wait; I'm sure I replied to this before.

Doesn't that install successfully? I'm looking at the output and don't see any actual errors.
