### ISSUE TITLE
Unable to install on macOS

### ISSUE THREAD

**Issue by Rifdhan** [Rantanen/node-opus#49]
The installation fails with:

```
Traceback (most recent call last):
  File "./gyp-mac-tool", line 611, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./gyp-mac-tool", line 28, in main
    exit_code = executor.Dispatch(args)
  File "./gyp-mac-tool", line 43, in Dispatch
    return getattr(self, method)(*args[1:])
  File "./gyp-mac-tool", line 246, in ExecFilterLibtool
    if not libtool_re.match(line) and not libtool_re5.match(line):
TypeError: cannot use a string pattern on a bytes-like object
make: *** [Release/opus.a] Error 1
```

Full output log: https://pastebin.com/DAjLmR0t

Relevant versions:
macOS High Sierra
node.js v9.6.1
npm v5.6.0
node-gyp v3.6.2

Am I doing something wrong?

**Comment by Rantanen** [comment]
This seems like a problem with your development environment. The `TypeError` is a Python error from node-gyp. Maybe a python version incompatibility? I don't know what the requirements of node-gyp are for Python versions.

**Comment by Rifdhan** [comment]
Turns out node-gyp only works with Python 2.7 and not 3.X. Changing the global default to 2.7 worked, thanks!
