### ISSUE TITLE
Invalid ELF headers when installed on Docker container

### ISSUE THREAD

**Issue by jonesg504** [Rantanen/node-opus#50]
I keep getting invalid ELF header when I try and run on a docker container:
err :  Error: /opt/app/node_modules/node-opus/build/Release/node-opus.node: invalid ELF header

I have node_modules in my .dockerignore and am running npm install in the docker container when it is created

**Comment by jonesg504** [comment]
Nevermind, it is a problem with docker-compose ignoring .dockerignore. Running docker build works fine

**Comment by Rantanen** [comment]
Great to hear! I was despairing already. :)
