### ISSUE TITLE
you like installation error issues, right?

### ISSUE THREAD

**Issue by nikbrandt** [Rantanen/node-opus#55]
Good, because I've got another for you.

```
15 warnings generated.
  LIBTOOL-STATIC Release/opus.a
Traceback (most recent call last):
  File "./gyp-mac-tool", line 611, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./gyp-mac-tool", line 28, in main
    exit_code = executor.Dispatch(args)
  File "./gyp-mac-tool", line 43, in Dispatch
    return getattr(self, method)(*args[1:])
  File "./gyp-mac-tool", line 246, in ExecFilterLibtool
    if not libtool_re.match(line) and not libtool_re5.match(line):
TypeError: cannot use a string pattern on a bytes-like object
make: *** [Release/opus.a] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Nik/Desktop/Codage/node-opus-installation-test/node_modules/node-opus
gyp ERR! node -v v10.4.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN opus-installation-test@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-opus@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-opus@0.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Nik/.npm/_logs/2018-06-30T05_59_18_288Z-debug.log
```

 - Full chaotic log available [here (node-opus-test-log.txt)](https://github.com/Rantanen/node-opus/files/2151472/node-opus-test-log.txt) (sorry for file download, 750 KB is over pastebin's limit)
 - debug log is [here (pastebin)](https://pastebin.com/H86eGvNf)
 - I know this is all in the logs, but I'm running..
   - macOS High Sierra (v10.13.3)
   - Node.js v.10.4.1 (latest stable as of today)
   - npm v6.1 (latest)
   - node-gyp v3.6.2 (not sure why it won't use latest, running `node-gyp -v` logs `3.7.0`)
 - This was tested in an empty folder where I literally just typed `npm init` before trying to install node-opus

Thanks. Sorry to bother you, this is just.. beyond what I can fix myself :P 
It *could* be a node-gyp issue, not entirely sure.

**Comment by Rantanen** [comment]
```
TypeError: cannot use a string pattern on a bytes-like object
```

TypeError is a Python error. So this is a node-gyp issue (gyp being a piece of Python software).

My guess would be Python version incompatibility.

Googling for `node-gyp` + the error message yields some results, at least the following one had seemed to have one workaround:

https://github.com/node-ffi/node-ffi/issues/266

**Comment by Gymnophoria** [comment]
Ah, yes, it was indeed python. 

macOS High Sierra has Python 3 as the default `python` script, and neither `npm config set python python2.7` nor `node-gyp rebuild --python python2.7` worked, so I had to go into `/usr/local/bin` and replace the `python` alias with an alias of the same name pointing to `python2.7` (you can also do this by [changing the PATH](https://github.com/libxmljs/libxmljs/issues/469))

node-gyp doesn't support python 3 and breaks (as of I think macOS Sierra+) unless `python` points to Python 2. Fun.

Anyways, issue resolved, thank you.

**Comment by nikbrandt** [comment]
Ah, yes, it was indeed python. 

macOS High Sierra has Python 3 as the default `python` script, and neither `npm config set python python2.7` nor `node-gyp rebuild --python python2.7` worked, so I had to go into `/usr/local/bin` and replace the `python` alias with an alias of the same name pointing to `python2.7` (you can also do this by [changing the PATH](https://github.com/libxmljs/libxmljs/issues/469)).

node-gyp doesn't support python 3 and breaks (as of I think macOS Sierra+) unless `python` points to Python 2. Fun.

Anyways, issue resolved, thank you.
