### ISSUE TITLE
Opus 1.3 wonderings

### ISSUE THREAD

**Issue by bossesand** [Rantanen/node-opus#58]
Do you have any idea if this package would work with opus 1.3-rc ?
I would like to test the ambisonic experimental features.

**Comment by Rantanen** [comment]
Currently the included Opus version is 1.1.

I'm not sure what Opus 1.3 would require. Do you know if it it is fully backwards compatible with 1.1/etc.?

**Comment by thijstriemstra** [comment]
> Do you know if it it is fully backwards compatible with 1.1/etc.?

Looks like it, no mention of backward incompatibilities here: http://opus-codec.org/release/dev/2018/06/01/libopus-1_3_rc.html

**Comment by bossesand** [comment]
Probably no issues as latest Firefox has implemented 1.3

Bo-Erik

**Comment by Rantanen** [comment]
I'm archiving the repository for lack of interest in maintaining it. Sorry I never got to deal with this issue. Please see [@discordjs/opus](https://github.com/discordjs/opus) for an alternative implementation that is based this project but uses more stable Node.js module technology that should break less between Node.js versions.
