### ISSUE TITLE
NPM Install Issues ( Logs provided)

### ISSUE THREAD

**Issue by PapaBeans** [Rantanen/node-opus#66]
Hello!

 I just want to preface this with the things I have tried.
I have uninstalled vs2015 and installed the build tools. 
I've removed all python versions and it's auto installed 2.7.14
I've followed other small suggestions on other issue tickets I've found.

That said, it seems to have an issue with the install script. 
Here is my log file after fixing my build tools (as far as I know)
https://hastebin.com/qibuvature.rb

Any help is  greatly appreciated!
Thank you for your time.

**Comment by xzessmedia** [comment]
run `npm install` in console as administrator

**Comment by Rantanen** [comment]
I'm archiving the repository for lack of interest in maintaining it. Sorry I never got to deal with this issue. Please see [@discordjs/opus](https://github.com/discordjs/opus) for an alternative implementation that is based this project but uses more stable Node.js module technology that should break less between Node.js versions.
