### ISSUE TITLE
Concencating AudioBuffer objects into single file

### ISSUE THREAD

**Issue by thijstriemstra** [Rantanen/node-opus#67]
I'm trying to stitch an incoming stream of `AudioBuffer` objects, received over a websocket connection, into a single file. Any pointers how this would be done using node-opus?

**Comment by Rantanen** [comment]
I'm archiving the repository for lack of interest in maintaining it. Sorry I never got to deal with this issue. Please see [@discordjs/opus](https://github.com/discordjs/opus) for an alternative implementation that is based this project but uses more stable Node.js module technology that should break less between Node.js versions.
