### ISSUE TITLE
Error to install Node-opus

### ISSUE THREAD

**Issue by FellGill** [Rantanen/node-opus#74]
My error:
https://hastebin.com/fomakodubo.pl

An idea ?

**Comment by Rantanen** [comment]
> C:\\Users\\Fellgill\\Desktop\\Dev\\Discord\\Bot\\KazunoriCanary\\KazunoriBot\\no
> de_modules\\ref\\build\\binding.vcxproj(20,3): error MSB4019: Le projet importé
> \"C:\\Microsoft.Cpp.Default.props\" est introuvable. Vérifiez que le chemin d'ac
> cès dans la déclaration <Import> est correct et que le fichier existe sur le dis
> que.

I'm guessing this is another environment lacking the build tools for C++ Node.js addons. Sorry, nothing that node-opus can fix.
