### ISSUE TITLE
Error: Could not locate the bindings file. Tried:

### ISSUE THREAD

**Issue by oceansync** [Rantanen/node-opus#78]
Error occurs for node-opus, anyone suggest a fix?
I tried removing node_modules folder but no use and I tried reinstalling node-opus but still the same error.

```
I could not join the voice channel: Error: Could not locate the bindings file. Tried:
 → /etc/valk/node_modules/node-opus/build/node-opus.node
 → /etc/valk/node_modules/node-opus/build/Debug/node-opus.node
 → /etc/valk/node_modules/node-opus/build/Release/node-opus.node
 → /etc/valk/node_modules/node-opus/out/Debug/node-opus.node
 → /etc/valk/node_modules/node-opus/Debug/node-opus.node
 → /etc/valk/node_modules/node-opus/out/Release/node-opus.node
 → /etc/valk/node_modules/node-opus/Release/node-opus.node
 → /etc/valk/node_modules/node-opus/build/default/node-opus.node
 → /etc/valk/node_modules/node-opus/compiled/11.5.0/linux/x64/node-opus.node
```

**Comment by Rantanen** [comment]
npm install should compile the native add-on, which results in the binary binding file. Looks like a problem with npm or node-gyp.

**Comment by Rantanen** [comment]
I'm archiving the repository for lack of interest in maintaining it. Sorry I never got to deal with this issue. Please see [@discordjs/opus](https://github.com/discordjs/opus) for an alternative implementation that is based this project but uses more stable Node.js module technology that should break less between Node.js versions.
