### ISSUE TITLE
Windows 10 Installation error

### ISSUE THREAD

**Issue by sspeekenbrink** [Rantanen/node-opus#80]
When I try installing Node-Opus, it gives me the following errors. I've tried re-installing Node.js, node-gyp, Visual Studio build tools, all to no avail.
The errors:

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:257:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Programming\Discord bot\node_modules\node-opus
gyp ERR! node -v v12.2.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-opus@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-opus@0.3.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

The full log: https://pastebin.com/Ua7a6iRP
Already thanks for helping!

**Comment by Rantanen** [comment]
Apparently Node.js has changed the APIs again. Node-opus has not been updated for the new APIs. A fast workaround would be to use an older Node version.

**Comment by sspeekenbrink** [comment]
Thanks! Made it work like a charm!

**Comment by Rantanen** [comment]
v0.3.2 should support Node 12.
