### ISSUE TITLE
Need help installing

### ISSUE THREAD

**Issue by tayacrystals** [Rantanen/node-opus#82]
Hi, i was trying to install node-opus but all the ways i tried resulted in an error.

My system and programs:
- Windows 10 Pro 64bit
- Node v12.0.0
- node-gyp v4.0.0
- windows build tools

Note: I am using pnpm, but the same error occured with npm

What i did:
`npm i node-opus`

Resulting output:
https://pastebin.com/ZDjVNjPm

If anyone here could help me, that would be awesome.
Thanks in advance, Linus.

**Comment by Rantanen** [comment]
> c:\users\linus\dev\bots\discord\gigabit\node_modules\.registry.npmjs.org\\**ref**\\1.3.5\node_modules\ref\src\binding.cc(222): error C2661: 'v8::Value::BooleanValue': no overloaded function takes 0 arguments [C:\U

That error comes from building the _ref_ module. I'm guessing _ref_ hasn't updated itself for Node v12. Although I'm somewhat confused on why `npm i node-opus` would try to install _ref_. As far as I know, it's a dependency of _ogg-packet_, which is an optional dependency for _node-opus_ and shouldn't be required.

I just did `npm i node-opus`  in a new project and while _ref_ errored on install, _node-opus_ installed successfully despite those errors:

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ref@1.3.5 (node_modules/ref):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ref@1.3.5 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ node-opus@0.3.2
added 6 packages from 11 contributors and audited 13 packages in 37.622s
found 0 vulnerabilities
```

**Comment by tayacrystals** [comment]
Ok, it appears to be an issue with pnpm, even though npm and pnpm spit out the same error when building, using npm works and pnpm doesn't. Thanks for the quick and helpful reply!
