### ISSUE TITLE
npm i node-opus does not work

### ISSUE THREAD

**Issue by ScarVite** [Rantanen/node-opus#88]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\flori\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   'node-opus'
1 verbose cli ]
2 info using npm@6.10.2
3 info using node@v12.3.1
4 verbose npm-session 6d7a5918c6ebaf67
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/node-opus 18ms (from cache)
8 silly pacote range manifest for node-opus@^0.3.2 fetched in 36ms
9 timing stage:loadCurrentTree Completed in 171ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 56ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule node-opus@0.3.2 checking installable status
17 silly removeObsoleteDep removing node-opus@0.3.2 from the tree as its been replaced by a newer version or is no longer required
18 silly removeObsoleteDep removing commander@2.20.0 from the tree as its been replaced by a newer version or is no longer required
19 silly removeObsoleteDep removing ogg-packet@1.0.1 from the tree as its been replaced by a newer version or is no longer required
20 silly removeObsoleteDep removing ref-struct@1.1.0 from the tree as its been replaced by a newer version or is no longer required
21 silly removeObsoleteDep removing debug@2.6.9 from the tree as its been replaced by a newer version or is no longer required
22 silly removeObsoleteDep removing ms@2.0.0 from the tree as its been replaced by a newer version or is no longer required
23 silly removeObsoleteDep removing ref@1.3.5 from the tree as its been replaced by a newer version or is no longer required
24 silly removeObsoleteDep removing bindings@1.2.1 from the tree as its been replaced by a newer version or is no longer required
25 silly removeObsoleteDep removing nan@2.14.0 from the tree as its been replaced by a newer version or is no longer required
26 http fetch GET 200 https://registry.npmjs.org/ogg-packet 52ms (from cache)
27 silly pacote range manifest for ogg-packet@^1.0.0 fetched in 55ms
28 silly resolveWithNewModule ogg-packet@1.0.1 checking installable status
29 http fetch GET 304 https://registry.npmjs.org/nan 162ms (from cache)
30 http fetch GET 304 https://registry.npmjs.org/bindings 167ms (from cache)
31 http fetch GET 304 https://registry.npmjs.org/commander 166ms (from cache)
32 silly pacote range manifest for nan@^2.14.0 fetched in 167ms
33 silly resolveWithNewModule nan@2.14.0 checking installable status
34 silly pacote range manifest for bindings@~1.2.1 fetched in 170ms
35 silly resolveWithNewModule bindings@1.2.1 checking installable status
36 silly pacote range manifest for commander@^2.9.0 fetched in 169ms
37 silly resolveWithNewModule commander@2.20.0 checking installable status
38 http fetch GET 200 https://registry.npmjs.org/ref-struct 3ms (from cache)
39 silly pacote range manifest for ref-struct@* fetched in 5ms
40 silly resolveWithNewModule ref-struct@1.1.0 checking installable status
41 http fetch GET 200 https://registry.npmjs.org/ref 7ms (from cache)
42 silly pacote range manifest for ref@1 fetched in 10ms
43 silly resolveWithNewModule ref@1.3.5 checking installable status
44 http fetch GET 304 https://registry.npmjs.org/debug 39ms (from cache)
45 silly pacote range manifest for debug@2 fetched in 41ms
46 silly resolveWithNewModule debug@2.6.9 checking installable status
47 http fetch GET 304 https://registry.npmjs.org/ms 37ms (from cache)
48 silly pacote version manifest for ms@2.0.0 fetched in 39ms
49 silly resolveWithNewModule ms@2.0.0 checking installable status
50 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 309ms
51 timing stage:loadIdealTree Completed in 382ms
52 silly currentTree Pilzmaster@0.0.1
52 silly currentTree +-- async-limiter@1.0.0
52 silly currentTree +-- async@0.1.22
52 silly currentTree +-- balanced-match@1.0.0
52 silly currentTree +-- base32@0.0.6
52 silly currentTree +-- bindings@1.2.1
52 silly currentTree +-- brace-expansion@1.1.11
52 silly currentTree +-- bufferutil@4.0.1
52 silly currentTree +-- commander@2.20.0
52 silly currentTree +-- concat-map@0.0.1
52 silly currentTree +-- date-format@2.0.0
52 silly currentTree +-- debug@2.6.9
52 silly currentTree +-- dht.js@0.2.16
52 silly currentTree +-- diff@1.0.8
52 silly currentTree +-- discord.js@11.5.1
52 silly currentTree +-- eyes@0.1.8
52 silly currentTree +-- ffmpeg@0.0.4
52 silly currentTree +-- flatted@2.0.1
52 silly currentTree +-- fs-extra@7.0.1
52 silly currentTree +-- fs.realpath@1.0.0
52 silly currentTree +-- glob@7.1.4
52 silly currentTree +-- graceful-fs@4.2.0
52 silly currentTree +-- html-entities@1.2.1
52 silly currentTree +-- inflight@1.0.6
52 silly currentTree +-- inherits@2.0.4
52 silly currentTree +-- jsonfile@4.0.0
52 silly currentTree +-- libsodium-wrappers@0.7.4
52 silly currentTree +-- libsodium@0.7.4
52 silly currentTree +-- log4js@4.4.0
52 silly currentTree | +-- debug@4.1.1
52 silly currentTree | `-- ms@2.1.2
52 silly currentTree +-- long@4.0.0
52 silly currentTree +-- m3u8stream@0.6.2
52 silly currentTree +-- math-round@1.0.0
52 silly currentTree +-- miniget@1.5.3
52 silly currentTree +-- minimatch@3.0.4
52 silly currentTree +-- minimist@0.0.10
52 silly currentTree +-- ms@2.0.0
52 silly currentTree +-- nan@2.14.0
52 silly currentTree +-- node-gyp-build@3.7.0
52 silly currentTree +-- node-torrent@0.2.2
52 silly currentTree +-- ogg-packet@1.0.1
52 silly currentTree +-- once@1.4.0
52 silly currentTree +-- optimist@0.6.1
52 silly currentTree +-- opusscript@0.0.6
52 silly currentTree +-- path-is-absolute@1.0.1
52 silly currentTree +-- prism-media@0.0.3
52 silly currentTree +-- ref-struct@1.1.0
52 silly currentTree +-- ref@1.3.5
52 silly currentTree +-- rfdc@1.1.4
52 silly currentTree +-- sax@1.2.4
52 silly currentTree +-- snekfetch@3.6.4
52 silly currentTree +-- streamroller@1.0.5
52 silly currentTree | +-- async@2.6.2
52 silly currentTree | +-- debug@3.2.6
52 silly currentTree | +-- lodash@4.17.15
52 silly currentTree | `-- ms@2.1.2
52 silly currentTree +-- tweetnacl@1.0.1
52 silly currentTree +-- universalify@0.1.2
52 silly currentTree +-- vows@0.8.2
52 silly currentTree +-- when@3.7.8
52 silly currentTree +-- wordwrap@0.0.3
52 silly currentTree +-- wrappy@1.0.2
52 silly currentTree +-- ws@6.2.1
52 silly currentTree `-- ytdl-core@0.29.5
53 silly idealTree Pilzmaster@0.0.1
53 silly idealTree +-- async-limiter@1.0.0
53 silly idealTree +-- async@0.1.22
53 silly idealTree +-- balanced-match@1.0.0
53 silly idealTree +-- base32@0.0.6
53 silly idealTree +-- bindings@1.2.1
53 silly idealTree +-- brace-expansion@1.1.11
53 silly idealTree +-- bufferutil@4.0.1
53 silly idealTree +-- commander@2.20.0
53 silly idealTree +-- concat-map@0.0.1
53 silly idealTree +-- date-format@2.0.0
53 silly idealTree +-- debug@2.6.9
53 silly idealTree +-- dht.js@0.2.16
53 silly idealTree +-- diff@1.0.8
53 silly idealTree +-- discord.js@11.5.1
53 silly idealTree +-- eyes@0.1.8
53 silly idealTree +-- ffmpeg@0.0.4
53 silly idealTree +-- flatted@2.0.1
53 silly idealTree +-- fs-extra@7.0.1
53 silly idealTree +-- fs.realpath@1.0.0
53 silly idealTree +-- glob@7.1.4
53 silly idealTree +-- graceful-fs@4.2.0
53 silly idealTree +-- html-entities@1.2.1
53 silly idealTree +-- inflight@1.0.6
53 silly idealTree +-- inherits@2.0.4
53 silly idealTree +-- jsonfile@4.0.0
53 silly idealTree +-- libsodium-wrappers@0.7.4
53 silly idealTree +-- libsodium@0.7.4
53 silly idealTree +-- log4js@4.4.0
53 silly idealTree | +-- debug@4.1.1
53 silly idealTree | `-- ms@2.1.2
53 silly idealTree +-- long@4.0.0
53 silly idealTree +-- m3u8stream@0.6.2
53 silly idealTree +-- math-round@1.0.0
53 silly idealTree +-- miniget@1.5.3
53 silly idealTree +-- minimatch@3.0.4
53 silly idealTree +-- minimist@0.0.10
53 silly idealTree +-- ms@2.0.0
53 silly idealTree +-- nan@2.14.0
53 silly idealTree +-- node-gyp-build@3.7.0
53 silly idealTree +-- node-opus@0.3.2
53 silly idealTree +-- node-torrent@0.2.2
53 silly idealTree +-- ogg-packet@1.0.1
53 silly idealTree +-- once@1.4.0
53 silly idealTree +-- optimist@0.6.1
53 silly idealTree +-- opusscript@0.0.6
53 silly idealTree +-- path-is-absolute@1.0.1
53 silly idealTree +-- prism-media@0.0.3
53 silly idealTree +-- ref-struct@1.1.0
53 silly idealTree +-- ref@1.3.5
53 silly idealTree +-- rfdc@1.1.4
53 silly idealTree +-- sax@1.2.4
53 silly idealTree +-- snekfetch@3.6.4
53 silly idealTree +-- streamroller@1.0.5
53 silly idealTree | +-- async@2.6.2
53 silly idealTree | +-- debug@3.2.6
53 silly idealTree | +-- lodash@4.17.15
53 silly idealTree | `-- ms@2.1.2
53 silly idealTree +-- tweetnacl@1.0.1
53 silly idealTree +-- universalify@0.1.2
53 silly idealTree +-- vows@0.8.2
53 silly idealTree +-- when@3.7.8
53 silly idealTree +-- wordwrap@0.0.3
53 silly idealTree +-- wrappy@1.0.2
53 silly idealTree +-- ws@6.2.1
53 silly idealTree `-- ytdl-core@0.29.5
54 silly install generateActionsToTake
55 timing stage:generateActionsToTake Completed in 10ms
56 silly diffTrees action count 1
57 silly diffTrees add node-opus@0.3.2
58 silly decomposeActions action count 8
59 silly decomposeActions fetch node-opus@0.3.2
60 silly decomposeActions extract node-opus@0.3.2
61 silly decomposeActions preinstall node-opus@0.3.2
62 silly decomposeActions build node-opus@0.3.2
63 silly decomposeActions install node-opus@0.3.2
64 silly decomposeActions postinstall node-opus@0.3.2
65 silly decomposeActions finalize node-opus@0.3.2
66 silly decomposeActions refresh-package-json node-opus@0.3.2
67 silly install executeActions
68 silly doSerial global-install 8
69 verbose correctMkdir C:\Users\flori\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
70 verbose makeCacheDir UID & GID are irrelevant on win32
71 verbose lock using C:\Users\flori\AppData\Roaming\npm-cache\_locks\staging-e81911e42f0222cb.lock for C:\Users\flori\Dropbox\Discord\Pilzmaster\node_modules\.staging
72 silly doParallel extract 1
73 silly extract node-opus@0.3.2
74 silly tarball trying node-opus@^0.3.2 by hash: sha512-o7hKgNncfbgF1j25lCK7cPqs9DEMroP3LWW0BMb/Ismc33cXo7LcaLqS0+/VV+NOotIy43fb7juLg6akflzBEw==
75 silly extract node-opus@^0.3.2 extracted to C:\Users\flori\Dropbox\Discord\Pilzmaster\node_modules\.staging\node-opus-d6360fcf (393ms)
76 timing action:extract Completed in 396ms
77 silly doReverseSerial unbuild 8
78 silly doSerial remove 8
79 silly doSerial move 8
80 silly doSerial finalize 8
81 silly finalize C:\Users\flori\Dropbox\Discord\Pilzmaster\node_modules\node-opus
82 timing audit submit Completed in 869ms
83 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 869ms
84 timing audit body Completed in 0ms
85 timing action:finalize Completed in 1463ms
86 silly doParallel refresh-package-json 1
87 silly refresh-package-json C:\Users\flori\Dropbox\Discord\Pilzmaster\node_modules\node-opus
88 timing action:refresh-package-json Completed in 10ms
89 silly doParallel preinstall 1
90 silly preinstall node-opus@0.3.2
91 info lifecycle node-opus@0.3.2~preinstall: node-opus@0.3.2
92 timing action:preinstall Completed in 2ms
93 silly doSerial build 8
94 silly build node-opus@0.3.2
95 info linkStuff node-opus@0.3.2
96 silly linkStuff node-opus@0.3.2 has C:\Users\flori\Dropbox\Discord\Pilzmaster\node_modules as its parent node_modules
97 timing action:build Completed in 2ms
98 silly doSerial global-link 8
99 silly doParallel update-linked 0
100 silly doSerial install 8
101 silly install node-opus@0.3.2
102 info lifecycle node-opus@0.3.2~install: node-opus@0.3.2
103 verbose lifecycle node-opus@0.3.2~install: unsafe-perm in lifecycle true
104 verbose lifecycle node-opus@0.3.2~install: PATH: C:\Users\flori\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\flori\Dropbox\Discord\Pilzmaster\node_modules\node-opus\node_modules\.bin;C:\Users\flori\Dropbox\Discord\Pilzmaster\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files\PuTTY\;C:\Program Files (x86)\Toshiba\Bluetooth Toshiba Stack\sys\;C:\Program Files (x86)\Toshiba\Bluetooth Toshiba Stack\sys\x64\;C:\Users\flori\.windows-build-tools\python27\;C:\Users\flori\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\flori\AppData\Roaming\npm\node_modules\windows-build-tools\node_modules\.bin;C:\Users\flori\AppData\Roaming\npm\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\flori\AppData\Local\Microsoft\WindowsApps;C:\Users\flori\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\flori\AppData\Local\GitHubDesktop\bin;C:\Users\flori\AppData\Roaming\npm;C:\Program Files\ffmpeg\bin\;;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps
105 verbose lifecycle node-opus@0.3.2~install: CWD: C:\Users\flori\Dropbox\Discord\Pilzmaster\node_modules\node-opus
106 silly lifecycle node-opus@0.3.2~install: Args: [ '/d /s /c', 'node-gyp rebuild' ]
107 silly lifecycle node-opus@0.3.2~install: Returned: code: 1  signal: null
108 info lifecycle node-opus@0.3.2~install: Failed to exec install script
109 timing action:install Completed in 6079ms
110 verbose unlock done using C:\Users\flori\AppData\Roaming\npm-cache\_locks\staging-e81911e42f0222cb.lock for C:\Users\flori\Dropbox\Discord\Pilzmaster\node_modules\.staging
111 timing stage:rollbackFailedOptional Completed in 123ms
112 timing stage:runTopLevelLifecycles Completed in 8677ms
113 silly saveTree Pilzmaster@0.0.1
113 silly saveTree +-- bufferutil@4.0.1
113 silly saveTree | `-- node-gyp-build@3.7.0
113 silly saveTree +-- discord.js@11.5.1
113 silly saveTree | +-- long@4.0.0
113 silly saveTree | +-- prism-media@0.0.3
113 silly saveTree | +-- snekfetch@3.6.4
113 silly saveTree | +-- tweetnacl@1.0.1
113 silly saveTree | `-- ws@6.2.1
113 silly saveTree |   `-- async-limiter@1.0.0
113 silly saveTree +-- ffmpeg@0.0.4
113 silly saveTree | `-- when@3.7.8
113 silly saveTree +-- libsodium-wrappers@0.7.4
113 silly saveTree | `-- libsodium@0.7.4
113 silly saveTree +-- math-round@1.0.0
113 silly saveTree +-- node-opus@0.3.2
113 silly saveTree | +-- bindings@1.2.1
113 silly saveTree | +-- commander@2.20.0
113 silly saveTree | +-- nan@2.14.0
113 silly saveTree | `-- ogg-packet@1.0.1
113 silly saveTree |   `-- ref-struct@1.1.0
113 silly saveTree |     +-- debug@2.6.9
113 silly saveTree |     | `-- ms@2.0.0
113 silly saveTree |     `-- ref@1.3.5
113 silly saveTree +-- node-torrent@0.2.2
113 silly saveTree | +-- base32@0.0.6
113 silly saveTree | | `-- optimist@0.6.1
113 silly saveTree | |   +-- minimist@0.0.10
113 silly saveTree | |   `-- wordwrap@0.0.3
113 silly saveTree | +-- dht.js@0.2.16
113 silly saveTree | | `-- async@0.1.22
113 silly saveTree | +-- log4js@4.4.0
113 silly saveTree | | +-- date-format@2.0.0
113 silly saveTree | | +-- debug@4.1.1
113 silly saveTree | | | `-- ms@2.1.2
113 silly saveTree | | +-- flatted@2.0.1
113 silly saveTree | | +-- rfdc@1.1.4
113 silly saveTree | | `-- streamroller@1.0.5
113 silly saveTree | |   +-- async@2.6.2
113 silly saveTree | |   | `-- lodash@4.17.15
113 silly saveTree | |   +-- debug@3.2.6
113 silly saveTree | |   | `-- ms@2.1.2
113 silly saveTree | |   +-- fs-extra@7.0.1
113 silly saveTree | |   | +-- graceful-fs@4.2.0
113 silly saveTree | |   | +-- jsonfile@4.0.0
113 silly saveTree | |   | `-- universalify@0.1.2
113 silly saveTree | |   `-- lodash@4.17.15
113 silly saveTree | `-- vows@0.8.2
113 silly saveTree |   +-- diff@1.0.8
113 silly saveTree |   +-- eyes@0.1.8
113 silly saveTree |   `-- glob@7.1.4
113 silly saveTree |     +-- fs.realpath@1.0.0
113 silly saveTree |     +-- inflight@1.0.6
113 silly saveTree |     | +-- once@1.4.0
113 silly saveTree |     | | `-- wrappy@1.0.2
113 silly saveTree |     | `-- wrappy@1.0.2
113 silly saveTree |     +-- inherits@2.0.4
113 silly saveTree |     +-- minimatch@3.0.4
113 silly saveTree |     | `-- brace-expansion@1.1.11
113 silly saveTree |     |   +-- balanced-match@1.0.0
113 silly saveTree |     |   `-- concat-map@0.0.1
113 silly saveTree |     +-- once@1.4.0
113 silly saveTree |     `-- path-is-absolute@1.0.1
113 silly saveTree +-- opusscript@0.0.6
113 silly saveTree `-- ytdl-core@0.29.5
113 silly saveTree   +-- html-entities@1.2.1
113 silly saveTree   +-- m3u8stream@0.6.2
113 silly saveTree   | +-- miniget@1.5.3
113 silly saveTree   | `-- sax@1.2.4
113 silly saveTree   +-- miniget@1.5.3
113 silly saveTree   `-- sax@1.2.4
114 warn discord.js@11.5.1 requires a peer of erlpack@discordapp/erlpack but none is installed. You must install peer dependencies yourself.
115 warn discord.js@11.5.1 requires a peer of node-opus@^0.2.7 but none is installed. You must install peer dependencies yourself.
116 warn discord.js@11.5.1 requires a peer of sodium@^2.0.3 but none is installed. You must install peer dependencies yourself.
117 warn discord.js@11.5.1 requires a peer of @discordjs/uws@^10.149.0 but none is installed. You must install peer dependencies yourself.
118 warn Pilzmaster@0.0.1 No repository field.
119 warn Pilzmaster@0.0.1 license should be a valid SPDX license expression
120 verbose stack Error: node-opus@0.3.2 install: `node-gyp rebuild`
120 verbose stack Exit status 1
120 verbose stack     at EventEmitter.<anonymous> (C:\Users\flori\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:326:16)
120 verbose stack     at EventEmitter.emit (events.js:200:13)
120 verbose stack     at ChildProcess.<anonymous> (C:\Users\flori\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
120 verbose stack     at ChildProcess.emit (events.js:200:13)
120 verbose stack     at maybeClose (internal/child_process.js:1021:16)
120 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
121 verbose pkgid node-opus@0.3.2
122 verbose cwd C:\Users\flori\Dropbox\Discord\Pilzmaster
123 verbose Windows_NT 10.0.18950
124 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\flori\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "node-opus"
125 verbose node v12.3.1
126 verbose npm  v6.10.2
127 error code ELIFECYCLE
128 error errno 1
129 error node-opus@0.3.2 install: `node-gyp rebuild`
129 error Exit status 1
130 error Failed at the node-opus@0.3.2 install script.
130 error This is probably not a problem with npm. There is likely additional logging output above.
131 verbose exit [ 1, true ]

**Comment by Rantanen** [comment]
Can't see anything in the output indicating this would be a node-opus issue instead of a build environment issue.

**Comment by ScarVite** [comment]
@Rantanen could you help me working my way around havent found anything online

**Comment by Rantanen** [comment]
I don't really do Node.js development on Windows. The usual suspects are windows build tools (https://www.npmjs.com/package/windows-build-tools) and making sure that doesn't conflict with a possible pre-existing installation of Visual Studio.
