### ISSUE TITLE
Unable to Install on Windows x64

### ISSUE THREAD

**Issue by metype** [Rantanen/node-opus#97]
When attempting to install node opus I get this error:

> gyp ERR! configure error 
> gyp ERR! stack Error: Command failed: C:\Users\Metype\AppData\Local\Programs\Python\Python38\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
> gyp ERR! stack   File "<string>", line 1
> gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
> gyp ERR! stack                       ^
> gyp ERR! stack SyntaxError: invalid syntax
> gyp ERR! stack
> gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
> gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
> gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
> gyp ERR! System Windows_NT 10.0.18362
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd 

Based on what it says I'm assuming it expects Python 2, but I'm using Python 3.8, I don't know how to fix this.

**Comment by Hazmi35** [comment]
What node and npm version are you using?

**Comment by Rantanen** [comment]
I'm archiving the repository for lack of interest in maintaining it. Sorry I never got to deal with this issue. Please see [@discordjs/opus](https://github.com/discordjs/opus) for an alternative implementation that is based this project but uses more stable Node.js module technology that should break less between Node.js versions.
