### ISSUE TITLE
How to deal with 16-bit vs 8-bit audio and frame_size may be incorrectly named

### ISSUE THREAD

**Issue by anshul-kai** [Rantanen/node-opus#98]
Firstly, thanks for this library. I'm encountering some issues, particularly with 16-bit audio.  The examples and documentation don't specify how to deal with each case. Also, a single frame of stereo 16-bit audio is 4 bytes long but in your documentation, you are using a `frame_size` of 480. Is that supposed to be the number of samples to process?

**Comment by Rantanen** [comment]
I'm archiving the repository for lack of interest in maintaining it. Sorry I never got to deal with this issue. Please see [@discordjs/opus](https://github.com/discordjs/opus) for an alternative implementation that is based this project but uses more stable Node.js module technology that should break less between Node.js versions.
